export { default as Navbar } from './Navbar'
export { default as Hero } from './Hero'
export { default as About } from './About'
export { default as Instructors } from './Instructors'
export { default as Videos } from './Videos'
export { default as Footer } from './Footer'
export { default as Promotion } from './Promotion'